global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:4000"]
    metrics_path: "/api/health"

  - job_name: "ai-service"
    static_configs:
      - targets: ["ai:5000"]
    metrics_path: "/health"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
