CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TEXT SEARCH CONFIGURATION arabic_english (COPY = simple);
ALTER TEXT SEARCH CONFIGURATION arabic_english
  ALTER MAPPING FOR asciiword, word WITH simple;
